blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions / پرسش‌ها و گفتگوها
    url: https://github.com/Kianmhz/GooseRelayVPN/discussions
    about: "Use Discussions for general questions or help. / برای سوالات عمومی از بخش Discussions استفاده کنید."
